_BASE_: "base_lofar.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v2_2000/"
DATASETS:
  TRAIN_SIZE: 2000
  TRAIN: ("train",)
  TEST: ("train","val")
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  STEPS: ()
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
  #EXTRA_EVAL: [1,500,1000,2500,10000]
