_BASE_: "../Base-RCNN-FPN.yaml"
EXPERIMENT_NAME: "v16_10"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v16_10/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LGZ_v8/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN_SIZE: 10
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  MAX_ITER: 20000 
  CHECKPOINT_PERIOD: 99999999999999999
TEST:
  EVAL_PERIOD: 30000
