_BASE_: "base_lofar.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v2_3000/"
DATASETS:
  TRAIN_SIZE: 3000
  TRAIN: ("train",)
  TEST: ("train","val")
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  STEPS: ()
  MAX_ITER: 60000 
  CHECKPOINT_PERIOD: 100000
TEST:
  EVAL_PERIOD: 999999999999
  #EXTRA_EVAL: [1,500,1000,2500,10000]
