_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/final_model/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 9999999999999999999
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 99999999999999999999999
TEST:
  EVAL_PERIOD: 9999999999999999
MODEL:
  WEIGHTS: "/home/rafael/mostertrij/tridentnet/output/final_model/model_0059999.pth"
#  ROI_HEADS:
#SCORE_THRESH_TEST: 0.0
#NMS_THRESH_TEST: 1.0
