_BASE_: "base_lofar.yaml"
EXPERIMENT_NAME: "v12"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v12/"
DATASETS:
  TEST: ("train","val")
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: (60000,90000)
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 30000
TEST:
  EVAL_PERIOD: 20000
  EXTRA_EVAL: [10,500,1000,2500,5000,10000]
