_BASE_: "base_lofar.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v14/"
DATASETS:
  TEST: ("train","val")
SOLVER:
  LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 30000
TEST:
  EVAL_PERIOD: 20000
  EXTRA_EVAL: [10,500,1000,2500,5000,10000]
