_BASE_: "base_lofar.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v1_cosineLR/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LGZ_v8_300arcsec/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val")
  IMAGE_DIR: "/data/mostertrij/data/frcnn_images/"
SOLVER:
  LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  STEPS: ()
  MAX_ITER: 200000 
  CHECKPOINT_PERIOD: 100000
TEST:
  EVAL_PERIOD: 20000
  EXTRA_EVAL: [1,500,1000,2500,10000]
