_BASE_: "base_lofar.yaml"
EXPERIMENT_NAME: ""
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LGZ_v7/LGZ_COCOstyle/annotations/"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v7_test/"
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  IMS_PER_BATCH: 4
  STEPS: ()
  MAX_ITER: 10000 
  CHECKPOINT_PERIOD: 1000000
TEST:
  EVAL_PERIOD: 20000
