_BASE_: "base_lofar_fast_rcnn"
MODEL:
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v4_1000/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 1000
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 2000000
#TEST:
EVAL_PERIOD: 20000
#EXTRA_EVAL: [1,500,1000,2500,5000,10000,15000]
