_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v4_all_withRot/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 9999999999999999999
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
