_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v4_all/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 999999999999999
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 300000
TEST:
  EVAL_PERIOD: 20000
