_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v3_precomputed_constantLR_no_box_reg/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
INPUT:
  ROTATION_ENABLED: False
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 15000 
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
  EXTRA_EVAL: [1,100]
