_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v3_precomputed0_removed_200kconstantLR_withRot/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/precomputed_bboxes0_remove_unresolved/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 200000 
  CHECKPOINT_PERIOD: 20000
TEST:
  REMOVE_UNRESOLVED: True
  EVAL_PERIOD: 20000
  EXTRA_EVAL: [1,100,1000,4000,8000]
