_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v17/"
DATASETS:
  TEST: ("train","val","test")
  TRAIN_SIZE: 9999999999999
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 30000
TEST:
  EVAL_PERIOD: 20000
  EXTRA_EVAL: [10,100,500,1000,2500,5000,10000]
