_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/v3_precomputed_removed_constantLR/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/precomputed_bboxes_remove_unresolved/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
INPUT:
  ROTATION_ENABLED: False
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 45000 
  CHECKPOINT_PERIOD: 4000
TEST:
  REMOVE_UNRESOLVED: True
  EVAL_PERIOD: 4000
  EXTRA_EVAL: [1,100,1000,2000,3000]
