_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/training_1field_kafka/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LGZ_precomputed_bboxes_300arcsec_1field/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val")
  TRAIN_SIZE: 100
INPUT:
  ROTATION_ENABLED: False
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 620
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
