_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/training_1field_unresolved_removed_kafka/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/training_1field_unresolved_removed_kafka/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
  TRAIN_SIZE: 999999999999
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
  REMOVE_UNRESOLVED: True
