_BASE_: "Base-TridentNet-Fast-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  # Determine mean of our GBR channels
  PIXEL_MEAN: [242.868, 246.401, 246.283]
  PIXEL_STD: [52.314, 15.5175, 44.389]
  BACKBONE:
      # Remove StopGrad at a specified stage so that no bottom layers are frozen
      # Default value is 2
      FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.333, 0.5, 1.0, 2.0, 3.0]]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  BASE_LR: 0.02
DATASETS:
  TRAIN: ("lofar_data1_train",)
  TEST: ("lofar_data1_val",)
INPUT:
    #  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
    MIN_SIZE_TRAIN: (600,)
    MAX_SIZE_TRAIN: (700,)
    MIN_SIZE_TEST: (600,)
    MAX_SIZE_TEST: (700,)
